translate all, please mind your eyes
SNWCreations/JKook pull request #11
Opened 2023-03-20 23:02 UTC by NatholDallas

2023-03-20 23:03 UTC, NatholDallas commented
7 commits, plz look my description

2023-03-21 04:51 UTC, SNWCreations commented
翻译不通过。疑似纯机翻，请自行认真翻译。
如这里不应该用 font ，应该是 text ，以表达这是一个"被应用了某种效果的文本"，愿意不是"这是一个斜体字体"。

2023-03-21 04:53 UTC, SNWCreations commented
另外，不要对同一个分支创建多个PR。警告一次。

2023-03-24 06:49 UTC, xiaoACE6716 approved these changes, later dismissed

2023-03-24 06:49 UTC, xiaoACE6716 commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +        if(!url.startsWith("http")){
我觉得这里可以把`if (!url.startsWith("http"))`改成`if (!url.startsWith("http://") || !url.startsWith("https://"))`

2023-03-24 10:14 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +        if(!url.startsWith("http")){
@xiaoACE6716 如果需要修改，请使用 Request Changes 类型。

2023-03-24 10:23 UTC, SNWCreations requested changes
参考 @xiaoACE6716 提供的建议修改。
另见我的要求。

2023-03-24 10:23 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +     * @param codeLanguage CodeLanguage, such as Java.
在出现举例时，应该用严谨的语言。
如 Java 应该用 "java" (包括引号) 替代。
我不能确定 ```Java 会生效。

2023-03-24 10:23 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +     * InLineCode.
语法不自然。

2023-03-24 10:23 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +     * All-@all user. <br>
此段需要重新翻译。

2023-03-24 10:23 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +     * Reference: <a href="https://img.kookapp.cn/assets/emoji.json">KookEmojiJson</a>.
KookEmojiJson 应该有空格分隔单词。

2023-03-24 10:23 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +     * Spoiler <br>
无意义的 br 标签。

2023-03-24 10:23 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +    /* Cut-off line. */
不是一个有效的 Javadoc 。

2023-03-24 10:27 UTC, SNWCreations requested changes
用自己的语言组织注释，而不是单纯照抄 KOOK 开发者文档的内容再翻译。
这是不负责的表现，若再次出现质量底下的情况，则此 PR 将关闭。

2023-03-24 10:27 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +     * @param eitRole RoleId.
使用 Role Id 而不是 RoleId。

2023-03-24 10:27 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +     * @param eit Parameter.
解释不详细。

2023-03-24 11:25 UTC, huanmeng-qwq commented
既然该类部分使用了@NotNull注解就应该全部都使用，请补全

2023-03-25 05:46 UTC, gehongyan requested changes

2023-03-25 05:46 UTC, gehongyan commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +                ">%s",
`>` 与正文间需要插入一个空格。

```suggestion
                "> %s",
```

2023-03-26 02:04 UTC, SNWCreations requested changes
见具体 review 内容。

2023-03-26 02:04 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +        if(!url.startsWith("http://") || !url.startsWith("https://")){
应该是 && ？

2023-03-26 02:04 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +     * @param codeLanguage CodeLanguage, such as "java", but not sure about "java" language can activate in "KooK".
仅保留第一个 "java" ，之后的解释应该移除。

2023-03-26 02:04 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +     * Inline code.
Inline 在 Java 中更多时候表示内联优化。有歧义。

2023-03-26 02:04 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +                references.replace(">", "\\>").replace("\n\n", "\n\\200d\n") + "\n\n"
有待测试。

2023-03-26 05:13 UTC, SNWCreations requested changes
见 review 内容

2023-03-26 05:13 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +        if (!url.startsWith("http://") && !url.startsWith("https://")) throw new IllegalArgumentException("must be http or https link");
应该保留 {}

2023-03-26 05:13 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +        if (emoji.contains(":")) throw new IllegalArgumentException("");
应该保留 {}

2023-03-26 05:17 UTC, SNWCreations commented
基本功能已实现。
现在需要做的是优化性能。
请考虑直接使用 StringBuilder ，因为 String.format 使用 Formatter ，匹配过程耗费的运算资源更多。

2023-03-26 07:16 UTC, SNWCreations requested changes
再改一处，即可合并。

2023-03-26 07:16 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +                .append("```")
这里应该补一个 \n

2023-03-26 07:17 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +                .append("```")
我的意思是 code 内容下面要补一个 \n 再写 ```

2023-03-26 10:40 UTC, huanmeng-qwq requested changes
方法返回值请添加`@NotNull`注解

2023-03-26 10:40 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +    public static String eitChannel(int channelID) {
channelID的类型应为String，详见: https://github.com/SNWCreations/JKook/blob/8ab20ebb109a3080132f5e123fefc9be70644a13/src/main/java/snw/jkook/entity/channel/Channel.java#L51

2023-03-26 10:40 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +    public static String underLine(@NotNull String underLine) {
缺少`@NotNull`注解

2023-03-26 10:40 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +    public static String spoiler(@NotNull String spoiler) {
缺少`@NotNull`注解

2023-03-26 10:40 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +    public static String serverEmoji(@NotNull String emojiName, @NotNull String emojiID) {
缺少`@NotNull`注解

2023-03-26 10:40 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +    public static String eitChannel(int channelID) {
缺少`@NotNull`注解

2023-03-26 10:40 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +            throw new IllegalArgumentException("");
缺少报错信息

2023-03-26 10:40 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +    public static String references(@NotNull String references) {
缺少`@NotNull`注解

2023-03-26 10:40 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +    public static String strikeThrough(@NotNull String strikeThrough) {
缺少`@NotNull`注解

2023-03-26 10:40 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +    public static String boldItalics(@NotNull String boldItalics) {
缺少`@NotNull`注解

2023-03-26 10:40 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +    public static String italic(@NotNull String italic) {
缺少`@NotNull`注解

2023-03-26 10:40 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +    public static String bold(@NotNull String bold) {
缺少`@NotNull`注解

2023-03-29 04:51 UTC, SNWCreations requested changes

2023-03-29 04:51 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +     * @param theme Theme, such as "success", but you should reference <a href="https://www.kookapp.cn/tools/message-builder.html#/card">Kook card message</a>.
为什么是消息编辑器链接？
我觉得可以在这里列出所有可用值。

2023-03-29 08:47 UTC, NatholDallas commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +     * @param theme Theme, such as "success", but you should reference <a href="https://www.kookapp.cn/tools/message-builder.html#/card">Kook card message</a>.
因为只有在消息编辑器中官方有提示彩色文本的markdown语法
目前还没有发现官方列举的所有可用值
因此可能会造成列举所有可用值不全的可能性

2023-03-29 10:07 UTC, huanmeng-qwq requested changes

2023-03-29 10:07 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +            throw new IllegalArgumentException("");
抛出的IllegalArgumentException未写明错误原因

2023-03-29 10:08 UTC, huanmeng-qwq submitted a review, later dismissed

2023-03-29 10:08 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +            throw new IllegalArgumentException();
抛出的IllegalArgumentException未写明错误原因

2023-03-29 12:58 UTC, SNWCreations requested changes

2023-03-29 12:58 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +            throw new IllegalArgumentException("can not be '[' or ']'.");
contain, NOT be.

2023-04-02 02:35 UTC, SNWCreations commented
可以合并。

2023-04-02 11:35 UTC, SNWCreations approved these changes
OK.

2023-04-02 11:35 UTC, SNWCreations commented on src/main/java/snw/jkook/util/KMarkdownHelper.java
> +@SuppressWarnings("unused")
这个SuppressWarning不需要。

2023-04-02 12:02 UTC, huanmeng-qwq approved these changes

2023-04-03 12:58 UTC, merged