Dev
SNWCreations/JKook pull request #15
Opened 2023-03-28 06:14 UTC by xiaoACE6716

add toString

2023-03-28 06:53 UTC, SNWCreations approved these changes
这部分内容可以合并。
等待 snw.jkook.entity.channel 下相关实体类的 toString 被覆写。

2023-03-30 05:02 UTC, huanmeng-qwq approved these changes

2023-03-30 05:02 UTC, huanmeng-qwq approved these changes

2023-03-31 10:45 UTC, SNWCreations requested changes
Channel.RolePermissionOverwrite 的 toString 未重写。

2023-03-31 11:09 UTC, xiaoACE6716 commented
> Channel.RolePermissionOverwrite 的 toString 未重写。

我不是写了么

2023-03-31 12:53 UTC, huanmeng-qwq commented
建议Event也加一波toString?

2023-04-02 12:17 UTC, huanmeng-qwq requested changes
部分Event缺少guild/role/user

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/entity/channel/Channel.java
> +                    "userName=" + user +
```suggestion
                    "user=" + user +
```
userName应该调用#getNickName

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/channel/ChannelCreateEvent.java
> +                "timeStamp=" + timeStamp +
缺少channel

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/channel/ChannelInfoUpdateEvent.java
> +                "timeStamp=" + timeStamp +
缺少channel

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/channel/ChannelMessageDeleteEvent.java
> +                ", messageId='" + messageId + '\'' +
缺少channel

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/channel/ChannelMessageEvent.java
> +                ", message=" + message +
缺少channel

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/channel/ChannelMessagePinEvent.java
> +                '}';
缺少channel

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/channel/ChannelMessageUnpinEvent.java
> +                ", operator=" + operator +
缺少channel

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/channel/ChannelMessageUpdateEvent.java
> +                ", content='" + content + '\'' +
缺少channel

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/guild/GuildBanUserEvent.java
> +                ", reason='" + reason + '\'' +
缺少guild

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/guild/GuildAddEmojiEvent.java
> +                ", emoji=" + emoji +
缺少guild

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/guild/GuildInfoUpdateEvent.java
> +                "timeStamp=" + timeStamp +
缺少guild

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/guild/GuildRemoveEmojiEvent.java
> +                ", emoji=" + emoji +
缺少guild

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/guild/GuildUnbanUserEvent.java
> +                ", operator=" + operator +
缺少guild

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/guild/GuildUpdateEmojiEvent.java
> +                ", emoji=" + emoji +
缺少guild

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/guild/GuildUserNickNameUpdateEvent.java
> +                '}';
缺少guild

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/role/RoleCreateEvent.java
> +                '}';
缺少role

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/role/RoleDeleteEvent.java
> +                "timeStamp=" + timeStamp +
缺少role

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/role/RoleInfoUpdateEvent.java
> +                "timeStamp=" + timeStamp +
缺少role

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/user/UserAddReactionEvent.java
> +                ", reaction=" + reaction +
缺少user

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/user/UserClickButtonEvent.java
> +                ", channel=" + channel +
缺少user

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/user/UserInfoUpdateEvent.java
> +        return "UserInfoUpdateEvent{}";
缺少user

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/user/UserJoinGuildEvent.java
> +                ", guild=" + guild +
缺少user

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/user/UserJoinVoiceChannelEvent.java
> +                ", channel=" + channel +
缺少user

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/user/UserLeaveGuildEvent.java
> +                ", guild=" + guild +
缺少user

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/user/UserLeaveVoiceChannelEvent.java
> +                ", channel=" + channel +
缺少user

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/user/UserOfflineEvent.java
> +                "timeStamp=" + timeStamp +
缺少user

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/user/UserOnlineEvent.java
> +                "timeStamp=" + timeStamp +
缺少user

2023-04-02 12:17 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/event/user/UserRemoveReactionEvent.java
> +                ", reaction=" + reaction +
缺少user

2023-04-02 16:30 UTC, xiaoACE6716 commented on src/main/java/snw/jkook/entity/channel/Channel.java
> +                    "userName=" + user +
6，这个好像是在我修正提交的时候弄混了，然而夏夜的要求是直接打印User对象

2023-04-03 04:32 UTC, huanmeng-qwq approved these changes

2023-04-03 12:55 UTC, SNWCreations approved these changes
OK.

2023-04-03 12:56 UTC, merged