添加权限接口
SNWCreations/JKook pull request #35
Opened 2024-09-01 07:59 UTC by huanmeng-qwq

closed #33

2024-09-01 08:48 UTC, SNWCreations requested changes
Definitely not acceptable. OP and tick are Minecraft-specific stuff.

2024-09-01 08:50 UTC, SNWCreations commented
Code cleanup & reformatting is not necessary in this PR.

2024-09-01 09:02 UTC, huanmeng-qwq commented
OP design can be considered as the administrator of Bot

2024-09-01 15:31 UTC, SNWCreations requested changes

2024-09-01 15:31 UTC, SNWCreations commented on src/main/java/snw/jkook/permissions/BotOperator.java
Should be removed as OP is Minecraft-specific stuff in our context.

2024-09-01 15:31 UTC, SNWCreations commented on src/main/java/snw/jkook/permissions/Permission.java
> +    public static final PermissionDefault DEFAULT_PERMISSION = PermissionDefault.OP;
That field should not exist if possible.

2024-09-01 15:31 UTC, SNWCreations commented on src/main/java/snw/jkook/permissions/Permissions.java
> +public final class Permissions {
Javadoc is missing

2024-09-01 15:31 UTC, SNWCreations commented on src/main/java/snw/jkook/plugin/PluginDescription.java
> +    public String getFullName() {
IDK why we add this

2024-09-01 15:33 UTC, SNWCreations commented
> OP design can be considered as the administrator of Bot

这不够清楚，用户可能会将其与KOOK服务器管理员混淆。

2024-09-10 14:24 UTC, SNWCreations commented
我的个人建议是不加入这个。

2024-09-10 14:25 UTC, huanmeng-qwq commented on src/main/java/snw/jkook/plugin/PluginDescription.java
> +    public String getFullName() {
方便实现侧在抛出异常时可以直接显示插件名和版本 不用重复调用`getName`和`getVersion`

2024-09-10 14:29 UTC, SNWCreations commented
应该作为单独PR。和本PR关联不强。

2024-09-10 14:32 UTC, huanmeng-qwq commented
该设定的存在可能导致实现起来更复杂，删掉挺好的。如果认为它应该存在的话可以尝试创建的新的pr添加。

2024-09-13 22:38 UTC, SNWCreations requested changes

2024-09-13 22:38 UTC, SNWCreations commented on src/main/java/snw/jkook/plugin/PluginDescription.java
> +    public String getFullName() {
应该作为单独PR添加。

2024-09-13 22:38 UTC, SNWCreations commented
其他部分可以通过。

2024-09-14 10:18 UTC, SNWCreations commented
请考虑重命名 snw.jkook.permissions.Permission 以避免与 snw.jkook.Permission 的冲突。

2024-09-17 05:26 UTC, SNWCreations approved these changes
OK

2024-09-17 05:27 UTC, merged